// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKWNyHQADVX2dJdsQkPk-ma40xVVMqJ9A',
    appId: '1:98508745305:web:034229f81a1ff23c5fdf48',
    messagingSenderId: '98508745305',
    projectId: 'flutter-e3e1d',
    authDomain: 'flutter-e3e1d.firebaseapp.com',
    storageBucket: 'flutter-e3e1d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0ag8X4-bwVuXjvDeczCHGJwmX-iNlzYE',
    appId: '1:98508745305:android:45126c24652457725fdf48',
    messagingSenderId: '98508745305',
    projectId: 'flutter-e3e1d',
    storageBucket: 'flutter-e3e1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_AIgF2J3yuMph0CVN7qU_PTsw_AeCS7g',
    appId: '1:98508745305:ios:01cfad782a4376e45fdf48',
    messagingSenderId: '98508745305',
    projectId: 'flutter-e3e1d',
    storageBucket: 'flutter-e3e1d.firebasestorage.app',
    iosBundleId: 'com.example.travelguide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_AIgF2J3yuMph0CVN7qU_PTsw_AeCS7g',
    appId: '1:98508745305:ios:01cfad782a4376e45fdf48',
    messagingSenderId: '98508745305',
    projectId: 'flutter-e3e1d',
    storageBucket: 'flutter-e3e1d.firebasestorage.app',
    iosBundleId: 'com.example.travelguide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKWNyHQADVX2dJdsQkPk-ma40xVVMqJ9A',
    appId: '1:98508745305:web:2034cde6600bbfd25fdf48',
    messagingSenderId: '98508745305',
    projectId: 'flutter-e3e1d',
    authDomain: 'flutter-e3e1d.firebaseapp.com',
    storageBucket: 'flutter-e3e1d.firebasestorage.app',
  );
}
